# Use this configuration to do a --multirun for all pairs of shifted environments,
# which ensures that each testing job will optimize beta for the given pair. See pa_diagvib_paper_eval.yaml to see the difference.
_target_: pametric.datautils.MultienvDataset
dset_list:
  # First one is original
  - _target_: src.data.components.diagvib_dataset.DiagVib6DatasetPA
    mnist_preprocessed_path: ${paths.data_dir}/dg/mnist_processed.npz
    cache_filepath: ${paths.data_dir}dg/dg_datasets/paper/test_${data.envs_name}${list_at_idx:${data.envs_index},0}.pkl
    seed: ${seed}

  # Second one is partially shifted
  - _target_: src.utils.datautils.apply_shift_ratio
    shift_ratio: ${auxiliary_args.pa_datashift.shift_ratio}
    ref_ds: ${list_at_idx:${callbacks.posterioragreement.dataset.dset_list},0} # the first dataset in this very list
    env_ds:
      _target_: src.data.components.diagvib_dataset.DiagVib6DatasetPA
      mnist_preprocessed_path: ${paths.data_dir}/dg/mnist_processed.npz
      cache_filepath: ${paths.data_dir}dg/dg_datasets/paper/test_${data.envs_name}${list_at_idx:${data.envs_index},1}.pkl
      seed: ${seed}


# Use:
# cache_filepath: ...${list_at_idx:${auxiliary_args.pa_datashift.envs_index},1}.pkl
# when the envs_index used to test are to be different from the ones used to optimize the beta.
