# Use this to do a single run (i.e. during training) in which beta is
# optimized with (0, 1), and then evaluated with (0, 1:5).
_target_: pametric.datautils.MultienvDataset
dset_list:
  - _target_: src.data.components.diagvib_dataset.DiagVib6DatasetPA
    mnist_preprocessed_path: ${paths.data_dir}/dg/mnist_processed.npz
    cache_filepath: ${data.test_dataset_dir}test_${diagvib_dataset.filename}0.pkl
    seed: ${seed}

  - _target_: src.data.components.diagvib_dataset.DiagVib6DatasetPA
    mnist_preprocessed_path: ${paths.data_dir}/dg/mnist_processed.npz
    cache_filepath: ${data.test_dataset_dir}test_${diagvib_dataset.filename}1.pkl
    seed: ${seed}
  
  - _target_: src.data.components.diagvib_dataset.DiagVib6DatasetPA
    mnist_preprocessed_path: ${paths.data_dir}/dg/mnist_processed.npz
    cache_filepath: ${data.test_dataset_dir}test_${diagvib_dataset.filename}2.pkl
    seed: ${seed}
  
  - _target_: src.data.components.diagvib_dataset.DiagVib6DatasetPA
    mnist_preprocessed_path: ${paths.data_dir}/dg/mnist_processed.npz
    cache_filepath: ${data.test_dataset_dir}test_${diagvib_dataset.filename}3.pkl
    seed: ${seed}
  
  - _target_: src.data.components.diagvib_dataset.DiagVib6DatasetPA
    mnist_preprocessed_path: ${paths.data_dir}/dg/mnist_processed.npz
    cache_filepath: ${data.test_dataset_dir}test_${diagvib_dataset.filename}4.pkl
    seed: ${seed}
  
  - _target_: src.data.components.diagvib_dataset.DiagVib6DatasetPA
    mnist_preprocessed_path: ${paths.data_dir}/dg/mnist_processed.npz
    cache_filepath: ${data.test_dataset_dir}test_${diagvib_dataset.filename}5.pkl
    seed: ${seed}