_target_: src.models.adv.AdvModule

n_classes: 10

net:
  _target_: src.models.components.adv.get_model
  model_name: ???
  dataset: cifar10
  threat_model: Linf
  model_dir: ${paths.data_dir}/adv/model_checkpoints