_target_: src.models.sentiment_analysis.SentimentAnalysisModule

n_classes: ${data.n_classes}

loss:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.SGD
  _partial_: True
  lr: 2e-5
  weight_decay: 0.01