# Used to debug some callbacks when calling _debug and _debug_train datasets.
defaults:
  # - feature_pairing.yaml
  # - pa_distances.yaml
  # - pa_plot.yaml
  - accuracy.yaml

  # Same as always:
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_summary:
  max_depth: -1

# I include it as null here to be able to override it in the script .sh file.
posterioragreement: null