accuracy_domains:
  _target_: src.callbacks.accuracy_domains.AccuracyDomains_Callback
  n_classes: ${model.net.n_classes}
  n_domains_train: ${len:'${data.train_config}'}
  n_domains_val: ${len:'${data.val_config}'}
  n_domains_test: ${len:'${data.test_config}'}