# https://lightning.ai/docs/pytorch/1.9.1/api/pytorch_lightning.callbacks.BatchSizeFinder.html#pytorch_lightning.callbacks.BatchSizeFinder

_target_: pametric.lightning.callbacks.MultienvBatchSizeFinder
mode: binsearch
steps_per_trial: 10
init_val: 2
max_trials: 10
batch_arg_name: batch_size

