# https://lightning.ai/docs/pytorch/1.9.1/api/pytorch_lightning.callbacks.BatchSizeFinder.html#pytorch_lightning.callbacks.BatchSizeFinder

_target_: pytorch_lightning.callbacks.BatchSizeFinder
mode: binsearch
steps_per_trial: 10
init_val: 1
max_trials: 20
batch_arg_name: batch_size

