defaults:
  - accuracy.yaml # Accuracy without domain distinction
  - model_checkpoint.yaml # Checkpoint on val/acc as always

  # Same as always:
  - model_summary.yaml
  - rich_progress_bar.yaml
  
  # PA only for label pairing
  - /callbacks@posterioragreement: pametric_label.yaml # PA metric with label pairing 

  - _self_

model_summary:
  max_depth: -1

normalization: null
posterioragreement:
  pairing_strategy: label
  pairing_csv: null

