# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.EarlyStopping.html

early_stopping_PA:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "PA(0,1)/logPA"
  min_delta: 0. # minimum change in the monitored quantity to qualify as an improvement
  patience: 100 #${trainer.max_epochs}/${callbacks.pa_lightning.log_every_n_epochs} # patience in epochs
  mode: "max"
  strict: False # whether to crash the training if monitor is not found in the validation metrics

  verbose: False # verbosity mode
  check_finite: True # when set True, stops training when the monitor becomes NaN or infinite
  stopping_threshold: null # stop training immediately once the monitored quantity reaches this threshold
  divergence_threshold: null # stop training as soon as the monitored quantity becomes worse than this threshold
  check_on_train_epoch_end: null # whether to run early stopping at the end of the training epoch
  # log_rank_zero_only: False  # this keyword argument isn't available in stable version