model_checkpoint_AFRpred:
  _target_: pametric.lightning.callbacks.PA_ModelCheckpoint
  patience: 0 #${callbacks.model_checkpoint_PA.patience}
  dirpath: ${callbacks.model_checkpoint_PA.dirpath}
  filename: afr_epoch_{epoch:03d}
  monitor: PA(0,1)/AFR_pred
  auto_insert_metric_name: False
  every_n_epochs: ${callbacks.posterioragreement.log_every_n_epochs}
  save_last: true

  verbose: False # verbosity mode
  save_top_k: 1 # save k best models (determined by above metric)
  save_weights_only: True # if True, then only the model’s weights will be saved
  train_time_interval: null # checkpoints are monitored at the specified time interval