# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint_PA:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "pa_epoch_{epoch:03d}"
  monitor: "val/logPA"
  mode: "max"
  save_last: False
  auto_insert_metric_name: False
  every_n_epochs: ${callbacks.pa_lightning.log_every_n_epochs} # check every n training epochs

  verbose: False # verbosity mode
  save_top_k: 1 # save k best models (determined by above metric)
  save_weights_only: False # if True, then only the model’s weights will be saved
  every_n_train_steps: null # number of training steps between checkpoints
  train_time_interval: null # checkpoints are monitored at the specified time interval
  save_on_train_epoch_end: null # whether to run checkpointing at the end of the training epoch or the end of validation
