defaults:
  - accuracy.yaml
  - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

accuracy:
  n_classes: ${data.n_classes}

model_checkpoint:
  save_weights_only: False

model_summary:
  max_depth: -1
