# @package _global_

defaults:
  - _self_
  - paths: default.yaml
  - data/dg/diagvib/modelselection/hue_idval_4.yaml

datasets_dir: ${paths.data_dir}/dg/dg_datasets/diagvib_modelselection/${folder_name}/

# Desired sizes of the datasets
# If the datasets are meant to have unique observations, do not surpass the sizes S_i = min_{shape}(SIZE_i)//num_envs, for i = {train, val, test}
SIZE_train: [4738, 5393, 4766, 4904, 4673, 4336, 4734, 5012, 4680, 4759]
SIZE_val: [1185, 1349, 1192, 1227, 1169, 1085, 1184, 1253, 1171, 1190]
SIZE_test: [980, 1135, 1032, 1010, 982, 892, 958, 1028, 974, 1009]

# Size of each environment
size_train: ${env_size_mnist:${SIZE_train},${shape},${len:${dataset_specifications.train.envs}}}
size_val: ${env_size_mnist:${SIZE_val},${shape},${len:${dataset_specifications.val.envs}}}
size_test: ${env_size_mnist:${SIZE_test},${shape},1} # test environments have always all the samples

# size_train: 40000
# size_val: 20000
# size_test: 10000

shape: ???

# hue, lightness, texture, position, scale
dataset_specifications: ???

extras:
  print_config: True
  ignore_warnings: True