# @package _global_

defaults:
  - _self_
  - paths: default.yaml

folder_name: hue_oodval_10
filename: env
datasets_dir: ${paths.data_dir}/dg/dg_datasets/diagvib_msel/${folder_name}/

# Desired sizes of the datasets
# If the datasets are meant to have unique observations, do not surpass the sizes S_i = min_{shape}(SIZE_i)//num_envs, for i = {train, val, test}
SIZE_train: [4738, 5393, 4766, 4904, 4673, 4336, 4734, 5012, 4680, 4759]
SIZE_val: [1185, 1349, 1192, 1227, 1169, 1085, 1184, 1253, 1171, 1190]
SIZE_test: [980, 1135, 1032, 1010, 982, 892, 958, 1028, 974, 1009]

# Size of each environment
size_train: ${env_size_mnist:${SIZE_train},${shape},${len:${dataset_specifications.train.envs}}}
size_val: ${env_size_mnist:${SIZE_val},${shape},${len:${dataset_specifications.val.envs}}}
size_test: ${env_size_mnist:${SIZE_test},${shape},1} # test environments have always all the samples

# size_train: 40000
# size_val: 20000
# size_test: 10000

shape: [0,1,2,3,4,5,6,7,8,9]

# hue, lightness, texture, position, scale
dataset_specifications:
  train:
    size: ${size_train}
    randperm: False # Set to False if we want label correspondence between environments.
    shape: ${shape}
    envs: 
      - [0,3,0,4,4]
      - [4,3,0,4,4]

  val:
    size: ${size_val}
    randperm: False
    shape: ${shape}
    envs:
      - [1,3,0,4,4]
      - [3,3,0,4,4]
      - [5,3,0,4,4]

  test:
    size: ${size_test}
    randperm: False # always False
    shape: ${shape}
    envs:
      - [2,3,0,4,4] 
      - [2,3,0,4,0]
      - [2,3,0,0,0]
      - [2,0,0,0,0]
      - [2,0,4,0,0]

extras:
  print_config: True
  ignore_warnings: True