_target_: src.models.erm.ERMMnist

n_classes: 2
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.backbone.Backbone
  net: resnet18
  pretrained: false
  input_channels: 3
  n_classes: 2  

